'number' + 23 + 32 // number2323 String
41 + 1 + 'number' // 42number String
null + 1 // 1 Number
'five' + + 'two' // fivetwo String
2 && 7 // 7 number
+'40' + +'2'; // 42 number
'10' - 5 === 6; // false
true + false // 1 number
'4px' - 3 // Nan
'4' - 3 // 1 number
'2' + 3 ** 2; // 29 number
12 / '6' // 2 number
23 + 42 + 'number' // 65number String
'10' + (5 === 6); //10false
'number' + 15 + 3 // number153 String